version: '3'
services:
  rails:
    command: rails s
    volumes:
      - .:/app
      - ./Gemfile.lock:/app/Gemfile.lock
      - /app/tmp
    build: .
    ports:
      - "3000:3000"
    environment:
      MUSIC_SNIPER_DATABASE_USERNAME: postgres
      MUSIC_SNIPER_DATABASE_PASSWORD: heydude
      MUSIC_SNIPER_DATABASE_PORT: 5432
      MUSIC_SNIPER_DATABASE_HOST: db
      MUSIC_SNIPER_DATABASE_URL: "postgres://user:pass@postgres:5432/datex_dev?pool=5&encoding=utf-8"
      RACK_ENV: development
      RAILS_HOST: http://localhost:3000
      RAILS_ENV: development
      RAILS_HOST: http://localhost:3000
      GOOGLE_AUTH_CLIENT_ID: 918861016270-1nsq4f1vov35ql1rkbrm63rkg89hn51e.apps.googleusercontent.com
    env_