version: '3'
services:
  rails:
    command: rails db:drop db:create db:migrate bundle exec rspec
    volumes:
      - .:/app
      - ./Gemfile.lock:/app/Gemfile.lock
      - /app/tmp
    build: .
    depends_on:
      - "dbtest"
    environment:
      MUSIC_SNIPER_DATABASE_USERN