version: '3'
services:
  rails:
    command: rails s
    volumes:
      - .:/app
      - ./Gemfile.lock:/app/Gemfile.lock
      - /app/tmp
    build: .
    ports:
      - "3000:3000"
    environment:
      MUSIC_SNIP